[tool.poetry]
name = "vulnpoetry"
version = "0.1.0"
authors = [""]
description = ""

[tool.poetry.dependencies]
python = "^3.9"
jupyter-core = "~4.11.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
